### ISSUE TITLE
the variable of  _inverted is't  used in ResultOrderBy

### ISSUE THREAD

**Issue by yuliman** [LunarBaseEngin/LunarBase#1]
after expirment,I found that the boolean variable of _inserted is not used in the  construction function,
the function order the resultSet by incoming field in ascending order,no matter the field _inserted is 
true or false.

**Comment by feiben** [comment]
in which construction function? If what your mentioned is under the Examples(ExamplesAdvanced...), you should implement your own order interface. Please check it out in [ResultOrderBy.java](https://github.com/LunarBaseEngin/LunarBase/blob/master/src/LCG/DB/EventHandler/Customized/ResultOrderBy.java) .
